### ISSUE TITLE
ROS2课程资料，第四、五、六的子章节无法访问

### ISSUE THREAD

**Issue by chengih** [zhangzhiwei-zzw/zhangzhiwei-zzw.github.io#1]
ROS2课程资料，第四、五、六的子章节无法访问，前面的章节能够正常打开
![image](https://github.com/user-attachments/assets/c443f705-8348-4adf-b11c-f7e5508e2169)
长时间加载后 404 not found

**Comment by zhangzhiwei-zzw** [comment]
这个资料我也是从其他地方拷贝来的，只有前几个章节
